function(set_arch_flags target arch)
  message(STATUS "Setting architecture flags for ${arch}")
  if(arch MATCHES "x86_64")
    target_compile_options(${target} PRIVATE -mavx2 -mpclmul -mbmi -mlzcnt)
  elseif(arch MATCHES "aarch64|arm64")
    if(APPLE)
      target_compile_options(${target} PRIVATE -mcpu=apple-m1)
    else()
      if(ENABLE_SVE2_128)
        target_compile_options(${target} PRIVATE -march=armv8-a+sve2 -msve-vector-bits=128)
      else()
        target_compile_options(${target} PRIVATE -march=armv8-a)
      endif()
    endif()
  elseif(arch MATCHES "riscv64")
    if(ENABLE_RVV_128)
      target_compile_options(${target} PRIVATE -march=rv64gcv_zvl128b -mrvv-vector-bits=zvl)
    endif()
  else()
    message(FATAL_ERROR "Unsupported architecture: ${arch}")
  endif()
endfunction()
