name: clang-format Check
on: [push, pull_request]
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - 'include/sonic'
          - 'benchmark'
          - 'tests'
          - 'example'
          - 'fuzz'
    steps:
    - uses: actions/checkout@v3
    - name: Run clang-format style check.
      uses: jidicula/clang-format-action@v4.9.0
      with:
        clang-format-version: '11'
        check-path: ${{ matrix.path }}
        fallback-style: 'Google'
