name: linux-clang
on: [push, pull_request]

jobs:
  unittest:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        llvm_version:
          - '11'
          - '13'
          - '15'

    steps:
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: ${{ matrix.llvm_version }}

      - uses: bazelbuild/setup-bazelisk@v2

      - uses: actions/checkout@v3

      - name: Run Unittest
        run : |
          export CC=clang
          export CXX=clang++
          bash ./scripts/unittest.sh -c
