name: linux-gcc
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install gcc9
        run : sudo apt-get install -y gcc-9 g++-9
      - name: Run Unittest in GCC
        run : export CC=gcc-9 && export CXX=g++-9 && source ./scripts/unittest.sh -g

