name: linux-clang
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install clang13
        run : sudo apt-get install -y clang-13 clang++-13
      - name: Run Unittest in Clang13
        run : export CC=clang-13 && export CXX=clang++-13 && source ./scripts/unittest.sh -c

