name: linux-clang
on: [push, pull_request]

jobs:
  unittest-llvm:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        llvm_version:
          - '11'
          - '13'
          - '15'
    env:
      CC: clang
      CXX: clang++

    steps:
      - uses: actions/checkout@v3

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: ${{ matrix.llvm_version }}

      - uses: bazelbuild/setup-bazelisk@v2

      - name: Run Unittest Use Bazel
        run : |
          bash ./scripts/unittest.sh -c
