# yaml-language-server: $schema=https://json-schema.org/draft-07/schema#
name: Test Coverage

permissions:
  contents: read
  actions: write
  id-token: write

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  test-coverage:
    name: bazel coverage
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    env:
      GCC_VERSION: 12

    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4

      - name: Read Bazel version
        run: |
          echo "BAZEL_VERSION=$(cat .bazelversion)" >> "$GITHUB_ENV"

      - name: Cache Bazel
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/bazel
            ~/.cache/bazelisk
          key: ${{ runner.os }}-bazel-${{ env.BAZEL_VERSION }}-${{ hashFiles('MODULE.bazel.lock', 'WORKSPACE.bzlmod', 'BUILD.bazel') }}
          restore-keys: |
            ${{ runner.os }}-bazel-${{ env.BAZEL_VERSION }}-
            ${{ runner.os }}-bazel-

      - name: Setup bazel
        uses: jwlawson/actions-setup-bazel@v2
        with:
          bazel-version: "${{ env.BAZEL_VERSION }}"

      - name: Setup GCC
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends gcc-12 g++-12
      - name: Install lcov
        run: |
          sudo apt-get install -y --no-install-recommends lcov

      - name: Coverage
        run: |
          bash ./scripts/run_coverage.sh
          genhtml --output bazel-coverage-html ./coverage.dat

      - name: upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: |
            bazel-coverage-html
            coverage.dat

      - name: Upload pull request coverage to CodeCov
        if: github.event_name == 'pull_request'
        uses: codecov/codecov-action@v4
        with:
          files: coverage.dat
          verbose: true
          fail_ci_if_error: true

      - name: Upload push coverage to CodeCov
        if: github.event_name == 'push'
        uses: codecov/codecov-action@v4
        with:
          use_oidc: true
          files: coverage.dat
          verbose: true
          fail_ci_if_error: true
